### ISSUE TITLE
Cannot Get the paclet

### ISSUE THREAD

**Issue by Ludwiggle** [cekdahl/jSoupLink#1]
Mathematica version 11.3

In[3]:= PacletInformation@"jsoupLink"

Out[3]= {"Name" -> "jsoupLink", "Version" -> "1.0.0", 
 "BuildNumber" -> "", "Qualifier" -> "", "WolframVersion" -> "10.0+", 
 "SystemID" -> All, 
 "Description" -> "HTML parser for Mathematica/Wolfram Language", 
 "Category" -> "", "Creator" -> "Calle Ekdahl", "Publisher" -> "", 
 "Support" -> "", "Internal" -> False, 
 "Location" -> 
  "/home/nicola/.Mathematica/Paclets/Repository/jsoupLink-1.0.0", 
 "Context" -> {"jsoupLink`"}, "Enabled" -> True, "Loading" -> Manual}

In[8]:= Needs["jsoupLink`"]

During evaluation of In[8]:= Get::noopen: Cannot open jsoupLink`.

During evaluation of In[8]:= Needs::nocont: Context jsoupLink` was not created when Needs was evaluated.

Out[8]= $Failed

**Comment by cekdahl** [comment]
Hi! Could you please evaluate ``FindFile["jsoupLink`"]`` and tell me what the result is?

**Comment by Ludwiggle** [comment]
$Failed

**Comment by cekdahl** [comment]
A Mathematica pro that I talked to suggested to try ``<< jsoupLink`jSoupLink` `` If this loads the package that can tell us a bit more about the problem you are having.

**Comment by Ludwiggle** [comment]
That works. Thanks

**Comment by cekdahl** [comment]
Great! I'm going to create a new release in a day or two that will in most likelihood fix this problem for you.
