### ISSUE TITLE
The search function is not working in obj["DOMTree"] window

### ISSUE THREAD

**Issue by Juddd** [cekdahl/jSoupLink#3]
Such as this code:
```
obj = Import["https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE41271", "HTMLDOM"];
obj["DOMTree"]
```
I want to get the CSS selector in `obj["DOMTree"]` window. So I want to search the text:"Samples (275)" to locate the target element on the window. I get nothing. But I'm pretty sure there's "Samples" text on the page. It is a bug?

**Comment by cekdahl** [comment]
I don't think that there is a search functionality in this tool. Maybe I'm not understanding the question correctly.

**Comment by Juddd** [comment]
I tried Ctrl+F to turn on the search text, which seemed necessary :)

**Comment by cekdahl** [comment]
I see. It's not been designed to work with ctrl+F, so I'm closing this issue.
